DROP TRIGGER IF EXISTS trg_tassignees_bump_task ON tasks.task_assignees;
DROP TRIGGER IF EXISTS trg_tlabels_bump_task ON tasks.task_labels;
DROP TRIGGER IF EXISTS trg_comments_bump_task ON tasks.comments;
DROP FUNCTION IF EXISTS tasks.child_bump_task();
DROP TRIGGER IF EXISTS trg_tasks_tombstone ON tasks.tasks;
DROP FUNCTION IF EXISTS tasks.task_tombstone();
DROP TABLE IF EXISTS tasks.task_tombstones;
DROP TRIGGER IF EXISTS trg_tasks_change_seq ON tasks.tasks;
DROP FUNCTION IF EXISTS tasks.bump_task_change_seq();
ALTER TABLE tasks.tasks DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS tasks.task_change_seq;
DROP TRIGGER IF EXISTS trg_bcomments_bump_board ON tasks.board_comments;
DROP TRIGGER IF EXISTS trg_labels_bump_board ON tasks.labels;
DROP TRIGGER IF EXISTS trg_stacks_bump_board ON tasks.stacks;
DROP FUNCTION IF EXISTS tasks.child_bump_board();
DROP TRIGGER IF EXISTS trg_boards_tombstone ON tasks.boards;
DROP FUNCTION IF EXISTS tasks.board_tombstone();
DROP TABLE IF EXISTS tasks.board_tombstones;
DROP TRIGGER IF EXISTS trg_boards_change_seq ON tasks.boards;
DROP FUNCTION IF EXISTS tasks.bump_board_change_seq();
ALTER TABLE tasks.boards DROP COLUMN IF EXISTS change_seq;
DROP SEQUENCE IF EXISTS tasks.board_change_seq;
